name: Build

env:
  GOPATH: /home/runner/work/go

on:
  push:
  pull_request:
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * 0' # weekly

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        go: ['1.9', '1.12', '1.13','^1']
    name: Build merry v1 with go version ${{ matrix.go }}

    steps:
      - uses: actions/setup-go@v2
        with:
          go-version: ${{ matrix.go }}
      - uses: actions/checkout@v2
      - name: Build
        run: |
          mkdir -p $GOPATH/bin
          export PATH=$PATH:$GOPATH/bin
          make tools all
          cd v2
          make tools coretest
  buildlatest:
    runs-on: ubuntu-latest
    name: Build v2 optional packages
    steps:
      - uses: actions/setup-go@v2
        with:
          go-version: '^1'
      - uses: actions/checkout@v2
      - name: Build
        run: |
          mkdir -p $GOPATH/bin
          export PATH=$PATH:$GOPATH/bin
          cd v2
          make tools all